### ISSUE TITLE
Reads passing vendor checks

### ISSUE THREAD

**Issue by burnsro** [kunalkathuria/SVXplorer#98]
Hi, 
Can you elaborate on the checking of discordant read for vendor problems, as I filtered the reads using samtool flags -F 512 but still keep getting this error.

**Comment by kunalkathuria** [comment]
Hi,

This portion of the README may be relevant: 

In addition, a split-alignment file and a file containing all fragments that align discordantly (using "samtools view -F 3842") should be provided as input. If unsure, scripts are provided in the scripts/ folder to create a discordant alignment file..

Please let us know if this doesn't work, and if so, what the exact error is. Thank you.

**Comment by burnsro** [comment]
Thanks, yes I ran the scripts provided to produce the discordant reads. 

But I get the error from writeDiscordantFragments.py, which seems to be the Assertion error

logging.debug("Assertion error on query name being same in writeDiscordants")
                sys.stderr.write("Please check if reads pass vendor checks \
                \n{0}\n{1}\nQuitting.\n" .format(q1,q2)).

So I was just wondering if you can elaborate what the script writeDiscordantFragments.py is using in the bam file to decide if a read fails the vendor check, because using samtools flag (-f 512) on my discordant reads to check if any don't pass vendor checks, everything seems fine.

**Comment by kunalkathuria** [comment]
The issue seems to be that the BAM file does not contain both first-in-pair ("left") and second-in-pair ("right") mates for the same read name. This can happen if you imposed an a priori mapping quality threshold for example, which took out one of the mates in an aligned pair. There are 2 choices in this case: you could re-align your original BAM file as recommended with BWA options in the README, or simply remove such cases from the discordant BAM file. Structural variant evidence based on PE reads requires both alignments to be present, and this option is a safeguard against incorrectly created BAM files. Also, SVXplorer provides an option to specify mapping threshold from the command line. Hope this helps!

**Comment by burnsro** [comment]
Got it, yes it does thank you!
